[2024-05-30T06:11:34.620+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tipico_dag.load_data_to_redshift scheduled__2024-05-30T06:00:00+00:00 [queued]>
[2024-05-30T06:11:34.650+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tipico_dag.load_data_to_redshift scheduled__2024-05-30T06:00:00+00:00 [queued]>
[2024-05-30T06:11:34.651+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-05-30T06:11:34.675+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_data_to_redshift> on 2024-05-30 06:00:00+00:00
[2024-05-30T06:11:34.687+0000] {standard_task_runner.py:60} INFO - Started process 5949 to run task
[2024-05-30T06:11:34.693+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tipico_dag', 'load_data_to_redshift', 'scheduled__2024-05-30T06:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/tipico_dag.py', '--cfg-path', '/tmp/tmpo9he6amh']
[2024-05-30T06:11:34.695+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask load_data_to_redshift
[2024-05-30T06:11:34.795+0000] {task_command.py:423} INFO - Running <TaskInstance: tipico_dag.load_data_to_redshift scheduled__2024-05-30T06:00:00+00:00 [running]> on host a71bb5ce980f
[2024-05-30T06:11:34.921+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tipico_dag' AIRFLOW_CTX_TASK_ID='load_data_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-05-30T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-30T06:00:00+00:00'
[2024-05-30T06:11:35.086+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tipico_etl.py", line 31, in load_data_to_redshift
    conn = redshift_hook.get_conn()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_sql.py", line 197, in get_conn
    conn_params = self._get_conn_params()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_sql.py", line 80, in _get_conn_params
    conn = self.conn
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_sql.py", line 76, in conn
    return self.get_connection(self.redshift_conn_id)  # type: ignore[attr-defined]
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 82, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 479, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `redshift_default` isn't defined
[2024-05-30T06:11:35.125+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=tipico_dag, task_id=load_data_to_redshift, execution_date=20240530T060000, start_date=20240530T061134, end_date=20240530T061135
[2024-05-30T06:11:35.155+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task load_data_to_redshift (The conn_id `redshift_default` isn't defined; 5949)
[2024-05-30T06:11:35.188+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-30T06:11:35.221+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
